### ISSUE TITLE
Windows test?

### ISSUE THREAD

**Issue by dansbandit** [FriedrichFroebel/python-djvulibre#7]
I'm trying package this for NixOS but it seems like it always runs the Windows test `djvu/dllpath.py`. It also fails when running `python setup.py test -v`

Is there anyway to disable this test?

```
$ python setup.py test -v
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing python_djvulibre.egg-info/PKG-INFO
writing dependency_links to python_djvulibre.egg-info/dependency_links.txt
writing requirements to python_djvulibre.egg-info/requires.txt
writing top-level names to python_djvulibre.egg-info/top_level.txt
reading manifest file 'python_djvulibre.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'doc/COPYING'
warning: no files found matching 'doc/credits'
adding license file 'COPYING'
writing manifest file 'python_djvulibre.egg-info/SOURCES.txt'
running build_ext
dllpath (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: dllpath (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: dllpath
Traceback (most recent call last):
  File "/nix/store/y0bgyc2q1wdy29ya89ykhsqys1mrjk5z-python3-3.9.16/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/dansbandit/python-djvulibre/djvu/dllpath.py", line 24, in <module>
    raise ImportError('This module is for Windows only')
ImportError: This module is for Windows only


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
```

**Comment by FriedrichFroebel** [comment]
Windows has never been supported properly and I thought that I had removed everything related to it during my initial clean-up after forking, but seem to have missed some stuff.

Nevertheless, if you do not use the deprecated `setup.py test` command, the *unittest* loader should never really stumble over the `djvu.dllpath` module, as it is not being imported anywhere: https://github.com/search?q=repo%3AFriedrichFroebel%2Fpython-djvulibre+dllpath&type=code. For CI testing, the following command is used and should not raise these issues: https://github.com/FriedrichFroebel/python-djvulibre/blob/d42be54e2309aa5240e0a0aacff5dbfeece86fd7/.github/workflows/ci.yml#L73

**Comment by dansbandit** [comment]
Thanks for the fast answer and solution!
