### ISSUE TITLE
Broken unittests?

### ISSUE THREAD

**Issue by dansbandit** [FriedrichFroebel/python-djvulibre#8]
It seems like the unittests are broken.

```
$ LC_ALL=C python -m unittest discover tests -v 
test_const (unittest.loader._FailedTest.test_const) ... ERROR
test_decode (unittest.loader._FailedTest.test_decode) ... ERROR
test_sexpr (unittest.loader._FailedTest.test_sexpr) ... ERROR

======================================================================
ERROR: test_const (unittest.loader._FailedTest.test_const)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_const
Traceback (most recent call last):
  File "/home/dansbandit/.local/share/pyenv/versions/3.11.4/lib/python3.11/unittest/loader.py", line 407, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dansbandit/.local/share/pyenv/versions/3.11.4/lib/python3.11/unittest/loader.py", line 350, in _get_module_from_name
    __import__(name)
  File "/home/dansbandit/djvu/python-djvulibre-FriedrichFroebel/tests/test_const.py", line 16, in <module>
    from djvu.const import (
  File "/home/dansbandit/djvu/python-djvulibre-FriedrichFroebel/djvu/const.py", line 20, in <module>
    import djvu.sexpr
ModuleNotFoundError: No module named 'djvu.sexpr'


======================================================================
ERROR: test_decode (unittest.loader._FailedTest.test_decode)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_decode
Traceback (most recent call last):
  File "/home/dansbandit/.local/share/pyenv/versions/3.11.4/lib/python3.11/unittest/loader.py", line 407, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dansbandit/.local/share/pyenv/versions/3.11.4/lib/python3.11/unittest/loader.py", line 350, in _get_module_from_name
    __import__(name)
  File "/home/dansbandit/djvu/python-djvulibre-FriedrichFroebel/tests/test_decode.py", line 24, in <module>
    from djvu.decode import (
ModuleNotFoundError: No module named 'djvu.decode'


======================================================================
ERROR: test_sexpr (unittest.loader._FailedTest.test_sexpr)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_sexpr
Traceback (most recent call last):
  File "/home/dansbandit/.local/share/pyenv/versions/3.11.4/lib/python3.11/unittest/loader.py", line 407, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dansbandit/.local/share/pyenv/versions/3.11.4/lib/python3.11/unittest/loader.py", line 350, in _get_module_from_name
    __import__(name)
  File "/home/dansbandit/djvu/python-djvulibre-FriedrichFroebel/tests/test_sexpr.py", line 24, in <module>
    from djvu.sexpr import (
ModuleNotFoundError: No module named 'djvu.sexpr'


----------------------------------------------------------------------
Ran 3 tests in 0.001s
```

**Comment by FriedrichFroebel** [comment]
Are you sure that the package is being built correctly and there are indeed no errors? Asking because compilation currently seems to fail for Cython 3.0 and thus pinning to Cython < 3.0 seems to be required (see #9).

**Comment by dansbandit** [comment]
```
$ python3 -m venv env
$ source env/bin/activate
$ pip install packaging wheel
$ pip install Cython==0.29.36
$ pip list
Package          Version
---------------- -------
Cython           0.29.36
packaging        23.1
pip              23.1.2
setuptools       65.5.0
wheel            0.41.0

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
$ pip install .
Processing /home/dansbandit/djvu/python-djvulibre-FriedrichFroebel
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: python-djvulibre
  Building wheel for python-djvulibre (pyproject.toml) ... done
  Created wheel for python-djvulibre: filename=python_djvulibre-0.8.8-cp311-cp311-linux_x86_64.whl size=2071123 sha256=470f0c8ab491a7208bfeb3ed66c51ee5b5123b8853e0982ec342efe4d4abf38e
  Stored in directory: /home/dansbandit/.cache/pip/wheels/c9/ec/d8/140f03ca2081562919b9c3f2d164981481873827d0868869bf
Successfully built python-djvulibre
Installing collected packages: python-djvulibre
Successfully installed python-djvulibre-0.8.8

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
$ LC_ALL=C python -m unittest discover tests -v
test_const (unittest.loader._FailedTest.test_const) ... ERROR
test_decode (unittest.loader._FailedTest.test_decode) ... ERROR
test_sexpr (unittest.loader._FailedTest.test_sexpr) ... ERROR

======================================================================
ERROR: test_const (unittest.loader._FailedTest.test_const)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_const
Traceback (most recent call last):
  File "/home/dansbandit/.local/share/pyenv/versions/3.11.4/lib/python3.11/unittest/loader.py", line 407, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dansbandit/.local/share/pyenv/versions/3.11.4/lib/python3.11/unittest/loader.py", line 350, in _get_module_from_name
    __import__(name)
  File "/home/dansbandit/djvu/python-djvulibre-FriedrichFroebel/tests/test_const.py", line 16, in <module>
    from djvu.const import (
  File "/home/dansbandit/djvu/python-djvulibre-FriedrichFroebel/djvu/const.py", line 20, in <module>
    import djvu.sexpr
ModuleNotFoundError: No module named 'djvu.sexpr'


======================================================================
ERROR: test_decode (unittest.loader._FailedTest.test_decode)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_decode
Traceback (most recent call last):
  File "/home/dansbandit/.local/share/pyenv/versions/3.11.4/lib/python3.11/unittest/loader.py", line 407, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dansbandit/.local/share/pyenv/versions/3.11.4/lib/python3.11/unittest/loader.py", line 350, in _get_module_from_name
    __import__(name)
  File "/home/dansbandit/djvu/python-djvulibre-FriedrichFroebel/tests/test_decode.py", line 24, in <module>
    from djvu.decode import (
ModuleNotFoundError: No module named 'djvu.decode'


======================================================================
ERROR: test_sexpr (unittest.loader._FailedTest.test_sexpr)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_sexpr
Traceback (most recent call last):
  File "/home/dansbandit/.local/share/pyenv/versions/3.11.4/lib/python3.11/unittest/loader.py", line 407, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dansbandit/.local/share/pyenv/versions/3.11.4/lib/python3.11/unittest/loader.py", line 350, in _get_module_from_name
    __import__(name)
  File "/home/dansbandit/djvu/python-djvulibre-FriedrichFroebel/tests/test_sexpr.py", line 24, in <module>
    from djvu.sexpr import (
ModuleNotFoundError: No module named 'djvu.sexpr'


----------------------------------------------------------------------
Ran 3 tests in 0.002s

FAILED (errors=3)
```

**Comment by FriedrichFroebel** [comment]
Could you please try to run `pip install --verbose .` for more output? Could you please check the content of the wheel and/or the listing of installed package files? CI uses some more recent package versions and just ran fine (package installation is checked by using `python -c 'import djvu.sexpr, djvu.decode'`), including Python 3.11.4 (although with the not yet merged changes to support Cython 3.0, which should not really make any difference here).

**Comment by dansbandit** [comment]
````
$ pip install --verbose .
Using pip 23.1.2 from /home/dansbandit/.local/share/.pyenv/versions/3.11.4/envs/python-djvulibre/lib/python3.11/site-packages/pip (python 3.11)
Processing /home/dansbandit/djvu/python-djvulibre-FriedrichFroebel
  Running command pip subprocess to install build dependencies
  Collecting setuptools
    Using cached setuptools-68.0.0-py3-none-any.whl (804 kB)
  Collecting wheel
    Using cached wheel-0.41.0-py3-none-any.whl (64 kB)
  Collecting Cython==0.29.36
    Using cached Cython-0.29.36-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
  Collecting packaging
    Using cached packaging-23.1-py3-none-any.whl (48 kB)
  Installing collected packages: wheel, setuptools, packaging, Cython
  Successfully installed Cython-0.29.36 packaging-23.1 setuptools-68.0.0 wheel-0.41.0

  [notice] A new release of pip is available: 23.1.2 -> 23.2.1
  [notice] To update, run: python3.11 -m pip install --upgrade pip
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  running egg_info
  writing python_djvulibre.egg-info/PKG-INFO
  writing dependency_links to python_djvulibre.egg-info/dependency_links.txt
  writing requirements to python_djvulibre.egg-info/requires.txt
  writing top-level names to python_djvulibre.egg-info/top_level.txt
  reading manifest file 'python_djvulibre.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'doc/COPYING'
  warning: no files found matching 'doc/credits'
  adding license file 'COPYING'
  writing manifest file 'python_djvulibre.egg-info/SOURCES.txt'
  Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating /tmp/pip-modern-metadata-s10o1btt/python_djvulibre.egg-info
  writing /tmp/pip-modern-metadata-s10o1btt/python_djvulibre.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-modern-metadata-s10o1btt/python_djvulibre.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-modern-metadata-s10o1btt/python_djvulibre.egg-info/requires.txt
  writing top-level names to /tmp/pip-modern-metadata-s10o1btt/python_djvulibre.egg-info/top_level.txt
  writing manifest file '/tmp/pip-modern-metadata-s10o1btt/python_djvulibre.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-modern-metadata-s10o1btt/python_djvulibre.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'doc/COPYING'
  warning: no files found matching 'doc/credits'
  adding license file 'COPYING'
  writing manifest file '/tmp/pip-modern-metadata-s10o1btt/python_djvulibre.egg-info/SOURCES.txt'
  creating '/tmp/pip-modern-metadata-s10o1btt/python_djvulibre-0.8.8.dist-info'
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: python-djvulibre
  Running command Building wheel for python-djvulibre (pyproject.toml)
  running bdist_wheel
  running build
  running build_py
  running build_ext
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/djvu
  copying build/lib.linux-x86_64-cpython-311/djvu/const.py -> build/bdist.linux-x86_64/wheel/djvu
  copying build/lib.linux-x86_64-cpython-311/djvu/sexpr.cpython-311-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/djvu
  copying build/lib.linux-x86_64-cpython-311/djvu/decode.cpython-311-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/djvu
  copying build/lib.linux-x86_64-cpython-311/djvu/__init__.py -> build/bdist.linux-x86_64/wheel/djvu
  running install_egg_info
  running egg_info
  writing python_djvulibre.egg-info/PKG-INFO
  writing dependency_links to python_djvulibre.egg-info/dependency_links.txt
  writing requirements to python_djvulibre.egg-info/requires.txt
  writing top-level names to python_djvulibre.egg-info/top_level.txt
  reading manifest file 'python_djvulibre.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'doc/COPYING'
  warning: no files found matching 'doc/credits'
  adding license file 'COPYING'
  writing manifest file 'python_djvulibre.egg-info/SOURCES.txt'
  Copying python_djvulibre.egg-info to build/bdist.linux-x86_64/wheel/python_djvulibre-0.8.8-py3.11.egg-info
  running install_scripts
  creating build/bdist.linux-x86_64/wheel/python_djvulibre-0.8.8.dist-info/WHEEL
  creating '/tmp/pip-wheel-3upoa5jq/.tmp-lsv_kl9c/python_djvulibre-0.8.8-cp311-cp311-linux_x86_64.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
  adding 'djvu/__init__.py'
  adding 'djvu/const.py'
  adding 'djvu/decode.cpython-311-x86_64-linux-gnu.so'
  adding 'djvu/sexpr.cpython-311-x86_64-linux-gnu.so'
  adding 'python_djvulibre-0.8.8.dist-info/COPYING'
  adding 'python_djvulibre-0.8.8.dist-info/METADATA'
  adding 'python_djvulibre-0.8.8.dist-info/WHEEL'
  adding 'python_djvulibre-0.8.8.dist-info/top_level.txt'
  adding 'python_djvulibre-0.8.8.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
  Building wheel for python-djvulibre (pyproject.toml) ... done
  Created wheel for python-djvulibre: filename=python_djvulibre-0.8.8-cp311-cp311-linux_x86_64.whl size=2052157 sha256=c532456e8a73dbdddac2c260aceb662db25513ed6494b909654e450b94d046c7
  Stored in directory: /home/dansbandit/.cache/pip/wheels/f8/5f/f9/974364335c2519c8863dc59e11a3309df45dbc782dbb554bc9
Successfully built python-djvulibre
Installing collected packages: python-djvulibre
Successfully installed python-djvulibre-0.8.8

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python3.11 -m pip install --upgrade pip
$ python -c 'import djvu.sexpr, djvu.decode'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'djvu.sexpr'
$ pip list
Package          Version
---------------- -------
Cython           0.29.36
packaging        23.1
pip              23.1.2
python-djvulibre 0.8.8
setuptools       65.5.0
wheel            0.41.0
```

**Comment by FriedrichFroebel** [comment]
The build/installation output looks right, so this should work. Does anything change if you call *pip* with `python -m pip` instead? If not, there seems to be some oddity with your setup which just started showing up recently.

**Comment by dansbandit** [comment]
```
$ python setup.py build_ext --inplace
running build_ext
copying build/lib.linux-x86_64-cpython-311/djvu/decode.cpython-311-x86_64-linux-gnu.so -> djvu
copying build/lib.linux-x86_64-cpython-311/djvu/sexpr.cpython-311-x86_64-linux-gnu.so -> djvu
$ LC_ALL=C python3 -m unittest discover tests -v                                                                                                                                    test_comparison1 (test_const.TestTextZones.test_comparison1) ... ok
test_comparison2 (test_const.TestTextZones.test_comparison2) ... ok
test_identity (test_const.TestTextZones.test_identity) ... ok
test_repr (test_const.TestTextZones.test_repr) ... ok
test_type (test_const.TestTextZones.test_type) ... ok
test_wildcard_import (test_const.WildcardImportTestCase.test_wildcard_import) ... ok
test1 (test_decode.AffineTransformsTestCase.test1) ... ok
test_bad_args (test_decode.AffineTransformsTestCase.test_bad_args) ... ok
test_context_cache (test_decode.ContextTestCase.test_context_cache) ... ok
test_bad_new (test_decode.DocumentsTestCase.test_bad_new) ... ok
test_export_ps (test_decode.DocumentsTestCase.test_export_ps) ... ok
test_new_document (test_decode.DocumentsTestCase.test_new_document) ... ok
test_nonexistent (test_decode.DocumentsTestCase.test_nonexistent) ... ok
test_nonexistent_ja (test_decode.DocumentsTestCase.test_nonexistent_ja) ... skipped 'unsupported locale setting'
test_save (test_decode.DocumentsTestCase.test_save) ... ok
test_jobs (test_decode.JobsTestCase.test_jobs) ... ok
test_bad_new (test_decode.MessagesTestCase.test_bad_new) ... ok
test_metadata (test_decode.MetadataTestCase.test_metadata) ... ok
test_bad_new (test_decode.PageJobsTestCase.test_bad_new) ... ok
test_decode (test_decode.PageJobsTestCase.test_decode) ... ok
test_bad_new (test_decode.PixelFormatsTestCase.test_bad_new) ... ok
test_grey (test_decode.PixelFormatsTestCase.test_grey) ... ok
test_packed_bits (test_decode.PixelFormatsTestCase.test_packed_bits) ... ok
test_palette (test_decode.PixelFormatsTestCase.test_palette) ... ok
test_rgb (test_decode.PixelFormatsTestCase.test_rgb) ... ok
test_rgb_mask (test_decode.PixelFormatsTestCase.test_rgb_mask) ... ok
test (test_decode.SexprTestCase.test) ... ok
test (test_decode.StreamsTestCase.test) ... ok
test_bad_new (test_decode.StreamsTestCase.test_bad_new) ... ok
test (test_decode.ThumbnailsTestCase.test) ... ok
test_version (test_decode.VersionTestCase.test_version) ... ok
test_wildcard_import (test_decode.WildcardImportTestCase.test_wildcard_import) ... ok
test_bytesio (test_sexpr.ExpressionParserAsciiTestCase.test_bytesio) ... ok
test_codecs_io (test_sexpr.ExpressionParserAsciiTestCase.test_codecs_io) ... ok
test_file_io_binary (test_sexpr.ExpressionParserAsciiTestCase.test_file_io_binary) ... ok
test_file_io_text (test_sexpr.ExpressionParserAsciiTestCase.test_file_io_text) ... ok
test_stringio (test_sexpr.ExpressionParserAsciiTestCase.test_stringio) ... ok
test_bytesio (test_sexpr.ExpressionParserNonAsciiTestCase.test_bytesio) ... ok
test_codecs_io (test_sexpr.ExpressionParserNonAsciiTestCase.test_codecs_io) ... ok
test_file_io_binary (test_sexpr.ExpressionParserNonAsciiTestCase.test_file_io_binary) ... ok
test_file_io_text (test_sexpr.ExpressionParserNonAsciiTestCase.test_file_io_text) ... ok
test_stringio (test_sexpr.ExpressionParserNonAsciiTestCase.test_stringio) ... ok
test_attr_from_file (test_sexpr.ExpressionParserTestCase.test_attr_from_file) ... ok
test_bad_file_io (test_sexpr.ExpressionParserTestCase.test_bad_file_io) ... ok
test_bad_io (test_sexpr.ExpressionParserTestCase.test_bad_io) ... ok
test_bad_unicode_io (test_sexpr.ExpressionParserTestCase.test_bad_unicode_io) ... ok
test_badstring (test_sexpr.ExpressionParserTestCase.test_badstring) ... ok
test_as_string_7 (test_sexpr.ExpressionWriterAsciiTestCase.test_as_string_7) ... ok
test_as_string_8 (test_sexpr.ExpressionWriterAsciiTestCase.test_as_string_8) ... ok
test_bytesio_7 (test_sexpr.ExpressionWriterAsciiTestCase.test_bytesio_7) ... ok
test_bytesio_8 (test_sexpr.ExpressionWriterAsciiTestCase.test_bytesio_8) ... ok
test_codecs_io_text_7 (test_sexpr.ExpressionWriterAsciiTestCase.test_codecs_io_text_7) ... ok
test_codecs_io_text_8 (test_sexpr.ExpressionWriterAsciiTestCase.test_codecs_io_text_8) ... ok
test_file_io_binary_7 (test_sexpr.ExpressionWriterAsciiTestCase.test_file_io_binary_7) ... ok
test_file_io_binary_8 (test_sexpr.ExpressionWriterAsciiTestCase.test_file_io_binary_8) ... ok
test_file_io_text_7 (test_sexpr.ExpressionWriterAsciiTestCase.test_file_io_text_7) ... ok
test_file_io_text_8 (test_sexpr.ExpressionWriterAsciiTestCase.test_file_io_text_8) ... ok
test_stringio_7 (test_sexpr.ExpressionWriterAsciiTestCase.test_stringio_7) ... ok
test_stringio_8 (test_sexpr.ExpressionWriterAsciiTestCase.test_stringio_8) ... ok
test_as_string_7 (test_sexpr.ExpressionWriterNonAsciiTestCase.test_as_string_7) ... ok
test_as_string_8 (test_sexpr.ExpressionWriterNonAsciiTestCase.test_as_string_8) ... ok
test_bytesio_7 (test_sexpr.ExpressionWriterNonAsciiTestCase.test_bytesio_7) ... ok
test_bytesio_8 (test_sexpr.ExpressionWriterNonAsciiTestCase.test_bytesio_8) ... ok
test_codecs_io_text_7 (test_sexpr.ExpressionWriterNonAsciiTestCase.test_codecs_io_text_7) ... ok
test_codecs_io_text_8 (test_sexpr.ExpressionWriterNonAsciiTestCase.test_codecs_io_text_8) ... ok
test_file_io_binary_7 (test_sexpr.ExpressionWriterNonAsciiTestCase.test_file_io_binary_7) ... ok
test_file_io_binary_8 (test_sexpr.ExpressionWriterNonAsciiTestCase.test_file_io_binary_8) ... ok
test_file_io_text_7 (test_sexpr.ExpressionWriterNonAsciiTestCase.test_file_io_text_7) ... ok
test_file_io_text_8 (test_sexpr.ExpressionWriterNonAsciiTestCase.test_file_io_text_8) ... ok
test_stringio_7 (test_sexpr.ExpressionWriterNonAsciiTestCase.test_stringio_7) ... ok
test_stringio_8 (test_sexpr.ExpressionWriterNonAsciiTestCase.test_stringio_8) ... ok
test_bad_file_io (test_sexpr.ExpressionWriterTestCase.test_bad_file_io) ... ok
test_bad_io (test_sexpr.ExpressionWriterTestCase.test_bad_io) ... ok
test_escape_unicode_type (test_sexpr.ExpressionWriterTestCase.test_escape_unicode_type) ... ok
test_reentrant (test_sexpr.ExpressionWriterTestCase.test_reentrant) ... ok
test_parse (test_sexpr.FloatExpressionsTestCase.test_parse) ... ok
test_0 (test_sexpr.IntExpressionsTestCase.test_0) ... ok
test_int (test_sexpr.IntExpressionsTestCase.test_int) ... ok
test_limits (test_sexpr.IntExpressionsTestCase.test_limits) ... ok
test_parse (test_sexpr.IntExpressionsTestCase.test_parse) ... ok
test_unpickle (test_sexpr.IntExpressionsTestCase.test_unpickle) ... ok
test1 (test_sexpr.ListExpressionsTestCase.test1) ... ok
test2 (test_sexpr.ListExpressionsTestCase.test2) ... ok
test_abc (test_sexpr.ListExpressionsTestCase.test_abc) ... ok
test_append (test_sexpr.ListExpressionsTestCase.test_append) ... ok
test_contains (test_sexpr.ListExpressionsTestCase.test_contains) ... ok
test_copy1 (test_sexpr.ListExpressionsTestCase.test_copy1) ... ok
test_copy2 (test_sexpr.ListExpressionsTestCase.test_copy2) ... ok
test_copy3 (test_sexpr.ListExpressionsTestCase.test_copy3) ... ok
test_count (test_sexpr.ListExpressionsTestCase.test_count) ... ok
test_delitem (test_sexpr.ListExpressionsTestCase.test_delitem) ... ok
test_extend (test_sexpr.ListExpressionsTestCase.test_extend) ... ok
test_index (test_sexpr.ListExpressionsTestCase.test_index) ... ok
test_inplace_add (test_sexpr.ListExpressionsTestCase.test_inplace_add) ... ok
test_insert (test_sexpr.ListExpressionsTestCase.test_insert) ... ok
test_pickle (test_sexpr.ListExpressionsTestCase.test_pickle) ... ok
test_pop (test_sexpr.ListExpressionsTestCase.test_pop) ... ok
test_remove (test_sexpr.ListExpressionsTestCase.test_remove) ... ok
test_reverse (test_sexpr.ListExpressionsTestCase.test_reverse) ... ok
test_string_expressions (test_sexpr.StringExpressionsTestCase.test_string_expressions) ... ok
test_ascii (test_sexpr.SymbolExpressionsTestCase.test_ascii) ... ok
test_nonascii (test_sexpr.SymbolExpressionsTestCase.test_nonascii) ... ok
test_ascii (test_sexpr.SymbolsTestCase.test_ascii) ... ok
test_inequality (test_sexpr.SymbolsTestCase.test_inequality) ... ok
test_nonascii (test_sexpr.SymbolsTestCase.test_nonascii) ... ok
test1 (test_sexpr.UnicodeExpressionsTestCase.test1) ... ok
test2 (test_sexpr.UnicodeExpressionsTestCase.test2) ... ok
test_version (test_sexpr.VersionTestCase.test_version) ... ok
test_wildcard_import (test_sexpr.WildcardImportTestCase.test_wildcard_import) ... ok
----------------------------------------------------------------------
Ran 109 tests in 0.314s

OK (skipped=1)
```

Installing with build_ext seems to fix it. Thanks for your help!

**Comment by FriedrichFroebel** [comment]
Ah, I see what your issue might be: You should not run the tests from the same directory as your Git checkout when you just installed the package (or delete the `djvu` directory beforehand). The current directory has a higher priority during import than the global installation, so without `build_ext --inplace`, you just attempt to import the original source without the shared objects - which fails as observed.
